### PR TITLE
Fix inifinite loop with 0 items.

### PR DESCRIPTION
**Pull request by rainwoodman**
There was an infinite loop when there are 0 items, due to a bug in _find_Pmin_Pmax_C.

Where there is no data, it returns -1, 0 instead of 0, 0, even though on each rank myPmin and myPmax is properly set to 0, 0.

### CODE REVIEW

**Comment by rainwoodman** [comment]
@sbird Please review.

This explains why it goes into an infinite loop. 
I think it explains why REQUIRE_GATHER masks the problem -- the reduction is no longer incorrect.

**Comment by rainwoodman** [comment]
There is a test that tests all combinations of items between 0, 1, 2 on 4 ranks with all tuning flags.

It should mimic the 12 rank MP-Gadget case fairly well, I assume.

**Comment by sbird** [comment]
Thanks! It looks ok naively, but I will test it out. This means that Pmin is no longer (-1, -1, -1) and thus non-empty? Is that ok?

**Comment by rainwoodman** [comment]
When there is no data, any non-empty range would work. 

As I looked into this closely, I realized the bisect starting from an empty range like 255, 255, 255; 0, 0, 0 has already violated the loop condition (left <= right); that's actually why bisect is never converging.

**Comment by sbird** [comment]
Ok, very good! Thanks!

**Comment by sbird** [comment]
Two small comments: you should make the arguments to _histogram and piter_accept unsigned char as well, to avoid compile warning

**Comment by sbird** [comment]
This fixes the infinite loop but not the problem with global sorting. This is with the mpsortdebug branch:

[ 000217.01 ] Begin Step 510, Time: 0.0777365 (e4000), Redshift: 11.864, Nf = 00000000524290, Systemstep: 0.000174603, Dloga: 0.00224
862, status: PM-Step
[ 000217.01 ] TotNumPart: 0000000524290 SPH 0000000262144 BH 0000000000 STAR 0000000000002 
[ 000217.01 ] Occupied:            0            1            2            3            4            5 dt
[ 000217.01 ]  X bin=14         4551         9007            0            0            0            0 0.0359779
[ 000217.01 ]  X bin=13        89487       171990            0            0            0            0 0.0179889
[ 000217.01 ]  X bin=12       123853        79158            0            0            0            0 0.00899447
[ 000217.01 ]  X bin=11        44205         1950            0            0            2            0 0.00449724
[ 000217.01 ]  X bin=10           48           39            0            0            0            0 0.00224862
[ 000217.01 ]                -----------------------------------
[ 000217.01 ] Total:          262144       262144            0            0            2            0  Sum:        524290
[ 000217.01 ] Tree construction.  (presently allocated=19.0273 MB)
[ 000217.01 ] Allocating memory for 46028 tree-nodes (MaxPart=65536).
[ 000217.01 ] Allocated 8.67816 MByte for BH-tree, (presently allocated 23.7578 MB)
[ 000217.02 ] Tree construction done.
[ 000217.02 ] Begin to compute FoF group catalogues. (allocated: 21.3242 MB)
[ 000217.02 ] Comoving linking length: 12.5
[ 000217.02 ] Start linking particles (presently allocated=22.3984 MB)
[ 000217.04 ] Linked 3903 particles 0.0153016 seconds
[ 000217.05 ] Linked 0 particles 0.00336034 seconds
[ 000217.05 ] Local groups found.
[ 000217.05 ] Group finding done.
[ 000217.05 ] Start finding nearest dm-particle (presently allocated=22.3984 MB)
[ 000217.05 ] fof-nearest iteration started
[ 000217.12 ] fof-nearest iteration 0: need to repeat for 0000000002 /0000262146 particles.
[ 000217.20 ] fof-nearest iteration 1: need to repeat for 0000000000 /0000262146 particles.
[ 000217.20 ] Attached gas and star particles to nearest dm particles.
[ 000217.21 ] Compiled local group data and catalogue.
[ 000217.21 ] Doing second FOF sort
[ 000217.21 ] Task 11: cur=(0 79469 64) prev= (0 108072 70)
[ 000217.21 ] Task 11: Ordering of global array is broken prev=140729743117936 d=10 (comp: 1). 
PID 187775 - process
TID 187775:
#0  0x00007f988972168c read
#1  0x0000560855287e31 show_backtrace
#2  0x000056085528dc45 endrun
#3  0x000056085527bdd4 fof_fof.constprop.0
#4  0x00005608552ba141 run
#5  0x0000560855271c4d main
#6  0x00007f988956c153 __libc_start_main
#7  0x0000560855272c6e _start

**Comment by rainwoodman** [comment]
Could you dump the data that went into the mp-sort call per rank with a fwrite?

**Comment by rainwoodman** [comment]
I've add the commit to mpsortdebug branch, but it takes me a long time to get to the crash. Send me the files if you get around to check this before mine arrives.

**Comment by sbird** [comment]
Thanks! I will - how shall we do the transfer? I don't have a cori account, but I have stampede and frontera

**Comment by sbird** [comment]
Oh, I see it is not the full particle table. I will just attach it here.

**Comment by sbird** [comment]
Here: 

[mpsort.tar.gz](https://github.com/rainwoodman/MP-sort/files/3801880/mpsort.tar.gz)

and the crash this time was:

[ 000245.80 ] fof-nearest iteration started
[ 000245.87 ] fof-nearest iteration 0: need to repeat for 0000000007 /0000262151 particles.
[ 000245.95 ] fof-nearest iteration 1: need to repeat for 0000000007 /0000262151 particles.
[ 000246.03 ] fof-nearest iteration 2: need to repeat for 0000000001 /0000262151 particles.
[ 000246.10 ] fof-nearest iteration 3: need to repeat for 0000000000 /0000262151 particles.
[ 000246.10 ] Attached gas and star particles to nearest dm particles.
[ 000246.11 ] Compiled local group data and catalogue.
[ 000246.11 ] Doing second FOF sort
[ 000246.11 ] Task 4: cur=(0 142160 76) prev= (0 237581 85)
[ 000246.11 ] Task 4: Ordering of global array is broken prev=140728967418896 d=3 (comp: 1).
PID 190167 - process
TID 190167:
#0  0x00007f969040868c read
#1  0x0000556029e4ce91 show_backtrace
#2  0x0000556029e52ca5 endrun
#3  0x0000556029e40e34 fof_fof.constprop.0
#4  0x0000556029e7f1a1 run
#5  0x0000556029e36c4d main
#6  0x00007f9690253153 __libc_start_main
#7  0x0000556029e37c6e _start

**Comment by rainwoodman** [comment]
I plumbed the data into python and couldn't reproduce this error there (the memory footprint in Python is slightly different than C). I will try to do this with C.

One thing I noticed though, is with Python the item 237581 landed on Task 4 after sorting, and 142160 landed on Task 3:

[[     0      0      0  60482      2]
 [     0      0      0  64449      2]
 [     0      0      0 142160      3]
 [     0      0      0 151248      3]
 [     0      0      0 154262      3]
 [     0      0      0 158361      3]
 [     0      0      0 174677      3]
 [     0      0      0 182357      3]
 [     0      0      0 186709      3]
 [     0      0      0 237581      4]
 [     0      0      0 120098      6]

Looks like prev and data is reversed, somehow?

**Comment by rainwoodman** [comment]
I get the same, correct result from C.

**Comment by rainwoodman** [comment]
2 : 60482 2 
2 : 64449 2 
3 : 142160 3 
3 : 151248 3 
3 : 154262 3 
3 : 158361 3 
3 : 174677 3 
3 : 182357 3 
3 : 186709 3 
4 : 237581 4 
6 : 120098 6 
....

**Comment by sbird** [comment]
hmm, I wonder if it is a bug I introduced with my earlier fix for the infinite loop? I will try it. Another possibility is that it might be initial-data-dependent. It changed position a little bit when I turned the address sanitizer on and off.

**Comment by sbird** [comment]
Here is a tarball with the "sorted" output as well:

[mpsort.tar.gz](https://github.com/rainwoodman/MP-sort/files/3802709/mpsort.tar.gz)
(it persists with the earlier fix reverted)

**Comment by rainwoodman** [comment]
I'd test with a clean mp-sort fetched from the fix-issue7 branch. How do you generate mpsort.c and mpsort.h? 

If you preserved the old file structure, then I could have just copied over the files without modification; or do a git fetch; git checkout in the submodule dir...

**Comment by rainwoodman** [comment]
My last message was lost. The file indeed contained a wrong entry in the output of MP-Sort from the mpsortdebug branch. Those 2 items are swapped.

I'm going to run this: https://github.com/MP-Gadget/MP-Gadget/tree/mpsort-issue7

**Comment by sbird** [comment]
ok - I am running it too.

**Comment by sbird** [comment]
I have the same crash in the same place with the mpsort-issue7 branch

**Comment by rainwoodman** [comment]
Mine ran to z=4.6 overnight, no crashing. 12 ranks with 1 thread (used to
crash).
I remember it was a bit tricky to make sure everything was recompiled, and
your mpsort code is synced to the right branch. (check with git status in
mp-sort code dir).

**Comment by sbird** [comment]
Aha! You are right, there was some not fully recompiled problem. It is a merge error! I will sort it out, thanks for the help.

**Comment by rainwoodman** [comment]
Probably reconsider the way you are embedding mpsort -- why not just copy the files instead of having a custom version and keeps merging?

I glanced through your changes. The major one seems to be adding mymalloc support?
Adding a mpsort_set_malloc function could solve that.

**Comment by sbird** [comment]
You are right, I will re-do the embedding in a more easily comparable way. mymalloc is the major thing that didn't go upstream already. Would you be open to an ifdef in upstream mpsort that makes mymalloc just malloc?

**Comment by rainwoodman** [comment]
Yes if you are in a rush.

I would prefer a mpsort_set_malloc that takes the full mymalloc and myfree
signature function pointers as the input. But I can do that upgrade one of
the weekends.

Yu

**Comment by sbird** [comment]
The other thing I wanted to do was to remove the code duplicated in MP-Gadget. This would be easier if I move the MPI_Alltoallv implementation in MP-Sort into its own file.

**Comment by sbird** [comment]
Why don't we merge this and the other PR and then I will submit another PR with some changes in MP-Sort's internal structure to make merging into MP-Gadget easier? Then we can talk about them and then re-do the merge afterwards.

**Comment by rainwoodman** [comment]
Sure. Did I get the merge permission? I sent you an invite.

I think the code dup on MPIU functions are still manageable. They are
relatively atomic functions with stable interfaces.

Copying them is cheaper than adding an extra lower level to the dependency.

That being said, if you want to stub the platform functions out, then a
struct of function pointers is likely the way to go more so than macros.

**Comment by sbird** [comment]
Oh yes you did. I will merge. Thanks.

**Pull request merged**
